import { jsPDF } from 'jspdf';
import type { ScanResult } from '@/types';
import type { TreatmentRecommendation } from '@/lib/treatments/treatment-engine';

export interface ReportData {
  scanResult: ScanResult;
  recommendations: TreatmentRecommendation[];
  fieldName?: string;
  gpsCoords?: { lat: number; lng: number };
  locale: string;
  region: string;
}

// Layout constants (A4 portrait, mm units)
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN_LEFT = 20;
const MARGIN_RIGHT = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;
const FOOTER_Y = PAGE_HEIGHT - 15;

// Color palette
const COLOR_PRIMARY: [number, number, number] = [34, 120, 60];
const COLOR_TEXT: [number, number, number] = [33, 33, 33];
const COLOR_SECONDARY: [number, number, number] = [100, 100, 100];
const COLOR_ACCENT: [number, number, number] = [220, 80, 40];
const COLOR_DIVIDER: [number, number, number] = [200, 200, 200];

function formatDate(locale: string): string {
  try {
    return new Date().toLocaleDateString(locale, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return new Date().toISOString().split('T')[0];
  }
}

function severityBar(level: number, maxLevel: number = 5): string {
  const filled = Math.min(level, maxLevel);
  const empty = maxLevel - filled;
  return '\u2588'.repeat(filled) + '\u2591'.repeat(empty);
}

function severityLabel(level: number): string {
  if (level <= 1) return 'Level 1 - Minimal';
  if (level === 2) return 'Level 2 - Mild';
  if (level === 3) return 'Level 3 - Moderate';
  if (level === 4) return 'Level 4 - Severe';
  return 'Level 5 - Critical';
}

function drawDivider(doc: jsPDF, y: number): number {
  doc.setDrawColor(...COLOR_DIVIDER);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_LEFT, y, PAGE_WIDTH - MARGIN_RIGHT, y);
  return y + 4;
}

function drawSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFontSize(13);
  doc.setTextColor(...COLOR_PRIMARY);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN_LEFT, y);
  return y + 7;
}

function drawWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number = 5
): number {
  const lines: string[] = doc.splitTextToSize(text, maxWidth) as string[];
  for (const line of lines) {
    if (y > FOOTER_Y - 10) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

function checkPageBreak(doc: jsPDF, y: number, requiredSpace: number): number {
  if (y + requiredSpace > FOOTER_Y - 10) {
    doc.addPage();
    return 20;
  }
  return y;
}

function drawFooter(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...COLOR_SECONDARY);
    doc.setFont('helvetica', 'normal');

    const footerText =
      'Generated by PeanutGuard AI | peanutguard.app | This report does not replace professional agronomist advice';
    const footerLines: string[] = doc.splitTextToSize(footerText, CONTENT_WIDTH) as string[];
    let footerY = FOOTER_Y;
    for (const line of footerLines) {
      doc.text(line, PAGE_WIDTH / 2, footerY, { align: 'center' });
      footerY += 3;
    }

    doc.setFontSize(7);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN_RIGHT, FOOTER_Y, {
      align: 'right',
    });
  }
}

/**
 * Generate a PDF diagnostic report on the farmer's device.
 * 100% client-side — no server call needed.
 * Target: <500KB file size, <2 seconds generation time.
 */
export async function generateReport(data: ReportData): Promise<Blob> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const primary = data.recommendations[0];
  const topPrediction = data.scanResult.predictions[0];
  const severity = primary?.severityLevel ?? data.scanResult.severityScore;

  let y = 20;

  // ── 1. Header ──
  doc.setFontSize(18);
  doc.setTextColor(...COLOR_PRIMARY);
  doc.setFont('helvetica', 'bold');
  doc.text('PeanutGuard AI', MARGIN_LEFT, y);
  y += 7;

  doc.setFontSize(11);
  doc.setTextColor(...COLOR_TEXT);
  doc.setFont('helvetica', 'normal');
  doc.text('Crop Health Report', MARGIN_LEFT, y);
  y += 6;

  doc.setFontSize(9);
  doc.setTextColor(...COLOR_SECONDARY);
  doc.text(formatDate(data.locale), MARGIN_LEFT, y);

  if (data.fieldName) {
    doc.text(`Field: ${data.fieldName}`, PAGE_WIDTH - MARGIN_RIGHT, y, { align: 'right' });
  }
  y += 4;

  if (data.gpsCoords) {
    doc.setFontSize(8);
    doc.text(
      `GPS: ${data.gpsCoords.lat.toFixed(5)}, ${data.gpsCoords.lng.toFixed(5)}`,
      MARGIN_LEFT,
      y
    );
    y += 4;
  }

  y = drawDivider(doc, y);

  // ── 2. Scan Image ──
  const imageDataUrl = data.scanResult.imageDataUrl;
  if (imageDataUrl && imageDataUrl.startsWith('data:image')) {
    try {
      const format = imageDataUrl.startsWith('data:image/png') ? 'PNG' : 'JPEG';
      const imgWidth = 60;
      const imgHeight = 45;

      y = checkPageBreak(doc, y, imgHeight + 10);
      doc.addImage(imageDataUrl, format, MARGIN_LEFT, y, imgWidth, imgHeight);
      y += imgHeight + 6;
    } catch {
      doc.setFontSize(8);
      doc.setTextColor(...COLOR_SECONDARY);
      doc.text('[Scan image could not be embedded]', MARGIN_LEFT, y);
      y += 6;
    }
  }

  // ── 3. Diagnosis Section ──
  y = checkPageBreak(doc, y, 35);
  y = drawSectionTitle(doc, 'Diagnosis', y);

  const diseaseName = primary
    ? (primary.disease.name[data.locale] ?? primary.disease.name['en'] ?? primary.disease.label)
    : (topPrediction?.diseaseLabel ?? 'Unknown');

  doc.setFontSize(14);
  doc.setTextColor(...COLOR_TEXT);
  doc.setFont('helvetica', 'bold');
  doc.text(diseaseName, MARGIN_LEFT, y);
  y += 6;

  if (primary?.disease.scientific_name) {
    doc.setFontSize(10);
    doc.setTextColor(...COLOR_SECONDARY);
    doc.setFont('helvetica', 'italic');
    doc.text(primary.disease.scientific_name, MARGIN_LEFT, y);
    y += 6;
  }

  // Confidence
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const confidence = topPrediction?.confidence ?? 0;
  const confidencePercent = Math.round(confidence * 100);
  doc.setTextColor(...COLOR_TEXT);
  doc.text(`Confidence: ${confidencePercent}%`, MARGIN_LEFT, y);
  y += 6;

  // Severity
  const severityText = `Severity: ${severityLabel(severity)}  ${severityBar(severity)}`;
  doc.setFontSize(10);
  if (severity >= 4) {
    doc.setTextColor(...COLOR_ACCENT);
  } else {
    doc.setTextColor(...COLOR_TEXT);
  }
  doc.setFont('helvetica', 'normal');
  doc.text(severityText, MARGIN_LEFT, y);
  y += 8;

  y = drawDivider(doc, y);

  // ── 4. Treatment Plan ──
  y = checkPageBreak(doc, y, 30);
  y = drawSectionTitle(doc, 'Treatment Plan', y);

  if (!primary) {
    doc.setFontSize(9);
    doc.setTextColor(...COLOR_SECONDARY);
    doc.setFont('helvetica', 'normal');
    doc.text('No specific treatments required at this time.', MARGIN_LEFT, y);
    y += 8;
  } else {
    // Organic treatments
    if (primary.organicTreatments.length > 0) {
      y = checkPageBreak(doc, y, 15);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(34, 139, 34);
      doc.text('[Organic]', MARGIN_LEFT, y);
      y += 5;

      for (const t of primary.organicTreatments) {
        y = checkPageBreak(doc, y, 20);
        const name = t.name[data.locale] ?? t.name['en'] ?? '';
        doc.setFontSize(10);
        doc.setTextColor(...COLOR_TEXT);
        doc.setFont('helvetica', 'bold');
        doc.text(name, MARGIN_LEFT + 2, y);
        y += 5;

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.text(`Active: ${t.active_ingredient ?? 'N/A'}`, MARGIN_LEFT + 4, y);
        y += 4;
        doc.text(`Dosage: ${t.dosage} | Frequency: ${t.frequency}`, MARGIN_LEFT + 4, y);
        y += 4;

        const brands = t.brands_by_region?.[data.region.toUpperCase()] ?? [];
        if (brands.length > 0) {
          doc.setTextColor(...COLOR_SECONDARY);
          doc.text(`Brands (${data.region.toUpperCase()}): ${brands.join(', ')}`, MARGIN_LEFT + 4, y);
          y += 5;
        } else {
          y += 1;
        }
      }
    }

    // Chemical treatments
    if (primary.chemicalTreatments.length > 0) {
      y = checkPageBreak(doc, y, 15);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(180, 80, 20);
      doc.text('[Chemical]', MARGIN_LEFT, y);
      y += 5;

      for (const t of primary.chemicalTreatments) {
        y = checkPageBreak(doc, y, 20);
        const name = t.name[data.locale] ?? t.name['en'] ?? '';
        doc.setFontSize(10);
        doc.setTextColor(...COLOR_TEXT);
        doc.setFont('helvetica', 'bold');
        doc.text(name, MARGIN_LEFT + 2, y);
        y += 5;

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.text(`Active: ${t.active_ingredient ?? 'N/A'}`, MARGIN_LEFT + 4, y);
        y += 4;
        doc.text(`Dosage: ${t.dosage} | Frequency: ${t.frequency}`, MARGIN_LEFT + 4, y);
        y += 4;

        const brands = t.brands_by_region?.[data.region.toUpperCase()] ?? [];
        if (brands.length > 0) {
          doc.setTextColor(...COLOR_SECONDARY);
          doc.text(`Brands (${data.region.toUpperCase()}): ${brands.join(', ')}`, MARGIN_LEFT + 4, y);
          y += 5;
        } else {
          y += 1;
        }
      }
    }

    // Cultural practices
    if (primary.culturalPractices.length > 0) {
      y = checkPageBreak(doc, y, 15);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLOR_PRIMARY);
      doc.text('[Cultural Practices]', MARGIN_LEFT, y);
      y += 5;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLOR_TEXT);
      for (const practice of primary.culturalPractices) {
        y = checkPageBreak(doc, y, 8);
        y = drawWrappedText(doc, `- ${practice}`, MARGIN_LEFT + 4, y, CONTENT_WIDTH - 8, 4.5);
        y += 1;
      }
    }
  }

  y = drawDivider(doc, y);

  // ── 5. Yield Impact ──
  y = checkPageBreak(doc, y, 20);
  y = drawSectionTitle(doc, 'Yield Impact', y);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  if (primary) {
    const yieldText = `Potential yield loss: ${primary.yieldImpact.min}% - ${primary.yieldImpact.max}%`;
    if (severity >= 4) {
      doc.setTextColor(...COLOR_ACCENT);
    } else {
      doc.setTextColor(...COLOR_TEXT);
    }
    doc.text(yieldText, MARGIN_LEFT, y);
  } else {
    doc.setTextColor(...COLOR_SECONDARY);
    doc.text('No yield impact data available.', MARGIN_LEFT, y);
  }
  y += 8;

  y = drawDivider(doc, y);

  // ── 5b. Confusion Pairs Warning ──
  if (primary && primary.disease.confusion_pairs && primary.disease.confusion_pairs.length > 0) {
    y = checkPageBreak(doc, y, 20);
    y = drawSectionTitle(doc, 'Similar Diseases (verify carefully)', y);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLOR_SECONDARY);
    doc.text(
      'This disease can be visually confused with the following. If uncertain, consult an agronomist:',
      MARGIN_LEFT,
      y
    );
    y += 5;

    for (const pairLabel of primary.disease.confusion_pairs) {
      y = checkPageBreak(doc, y, 6);
      doc.setTextColor(...COLOR_TEXT);
      doc.text(`- ${pairLabel.replace(/_/g, ' ')}`, MARGIN_LEFT + 4, y);
      y += 4.5;
    }
    y += 2;
    y = drawDivider(doc, y);
  }

  // ── 6. Follow-up ──
  y = checkPageBreak(doc, y, 15);
  y = drawSectionTitle(doc, 'Follow-up', y);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLOR_TEXT);
  const followUpDays = severity >= 4 ? 3 : severity >= 3 ? 7 : 14;
  doc.text(
    `Rescan in ${followUpDays} days to track progress and evaluate treatment effectiveness.`,
    MARGIN_LEFT,
    y
  );

  // ── 7. Footer ──
  drawFooter(doc);

  return doc.output('blob');
}

/**
 * Generate and trigger download of the PDF.
 */
export async function downloadReport(data: ReportData): Promise<void> {
  const blob = await generateReport(data);

  const dateStr = new Date().toISOString().split('T')[0];
  const fieldSlug = data.fieldName
    ? data.fieldName.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 20)
    : 'scan';
  const filename = `PeanutGuard_${fieldSlug}_${dateStr}.pdf`;

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.style.display = 'none';
  document.body.appendChild(link);
  link.click();

  setTimeout(() => {
    try {
      URL.revokeObjectURL(url);
    } catch {
      // URL may already be revoked
    }
    try {
      if (link.parentNode) {
        link.parentNode.removeChild(link);
      }
    } catch {
      // Link may already be removed (e.g. user navigated away)
    }
  }, 1000);
}
